// vim: set ft=cpp ts=8 sts=2 sw=2 tw=80 et ai si ci:
#ifndef _YAMAIL_DATA_ZEROCOPY_PARSER_NAMESPACE_H_
#define _YAMAIL_DATA_ZEROCOPY_PARSER_NAMESPACE_H_
#include <yamail/config.h>
#include <yamail/data/namespace.h>

#define YAMAIL_NS_DATA_ZC zerocopy /* ZeroCopy Buffers */
#define YAMAIL_FQNS_DATA_ZC YAMAIL_FQNS_DATA::YAMAIL_NS_DATA_ZC

#define YAMAIL_NS_DATA_ZC_BEGIN namespace YAMAIL_NS_DATA_ZC {
#define YAMAIL_NS_DATA_ZC_END }

#define YAMAIL_FQNS_DATA_ZC_BEGIN \
  YAMAIL_NS_BEGIN YAMAIL_NS_DATA_BEGIN YAMAIL_NS_DATA_ZC_BEGIN

#define YAMAIL_FQNS_DATA_ZC_END \
  YAMAIL_NS_DATA_ZC_END YAMAIL_NS_DATA_END YAMAIL_NS_END

// Alias zc = zerocopy
YAMAIL_NS_BEGIN
  YAMAIL_NS_DATA_BEGIN
    YAMAIL_NS_DATA_ZC_BEGIN YAMAIL_NS_DATA_ZC_END

namespace zc = YAMAIL_NS_DATA_ZC;
  YAMAIL_NS_DATA_END
YAMAIL_NS_END


#endif // _YAMAIL_DATA_ZEROCOPY_PARSER_NAMESPACE_H_
